### ISSUE TITLE
break apart argonaut

### ISSUE THREAD

**Issue by jdegoes** [purescript-contrib/purescript-argonaut#16]
* purescript-argonaut-core &mdash; Definition of `Json`, `foldJson`, and `Eq`, `Show`, `Ord`, etc., instances for `Json`, together with printing and parsing (which are native methods!). This will be a *very small* library with minimal dependencies, which other libraries can use to agree on what `Json` is.
 * purescript-argonaut-combinators &mdash; All the combinators and operators that make using Argonaut easy. These, in turn, are largely defined in terms of the fold methods, but some may be special-cased for performance reasons.
 * purescript-argonaut-serialization &mdash; EncodeJson / DecodeJson and instances for the world.
 * purescript-argonaut-zipper &mdash; For things like JCursor, JZipper, etc. Maybe there's a better name for this one or maybe it belongs somewhere else.

Thoughts?

**Comment by cryogenian** [comment]
Shall we make this repo aggregation like `purescript-base`?

**Comment by jdegoes** [comment]
Yes, this one should re-export the other modules in Data.Argonaut, and of course depend on them all in bower.
