### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by yemi** [purescript-contrib/purescript-argonaut#18]
Great lib! Seems like what i need for my project but find it very hard to use without documentation.

**Comment by thomashoneyman** [comment]
Despite the age of the issue, still wanted to give an update on the documentation for this set of libraries:

- Module documentation is [published on Pursuit](https://pursuit.purescript.org/packages/purescript-argonaut). 
- Argonaut, its basic data types, and its approach to JSON are documented in [purescript-argonaut-core](https://github.com/purescript-contrib/purescript-argonaut-core).
- Encoding and decoding PureScript types to and from `Json` is documented in [purescript-argonaut-codecs](https://github.com/purescript-contrib/purescript-argonaut-codecs).
- Manipulating `Json` using optics and `JCursor` is documented in [purescript-argonaut-traversals](https://github.com/purescript-contrib/purescript-argonaut-traversals)
