### ISSUE TITLE
Maintenance going forward

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/purescript-argonaut#19]
@jdegoes I assume this one is going to continue to be active. Do you want to keep this in contrib? Shall I count you as the maintainer?

Revelant: https://github.com/purescript/purescript/issues/1156

**Comment by jdegoes** [comment]
@paf31 Yes, this is quite active, & please count me as the maintainer. I do want to keep this in contrib (wait? is contrib shutting down or not???).

**Comment by paf31** [comment]
No, it'll stay open. I just want to identify maintainers. I'll write up some guidelines on the issue soon, but I think at least it will involve publicly identifying who is responsible for issues/PRs etc., either on GitHub or on Pursuit later.
