### ISSUE TITLE
export getFieldOptional (.??) from Data.Argonaut

### ISSUE THREAD

**Issue by cdepillabout** [purescript-contrib/purescript-argonaut#37]
It would be nice if [`getFieldOptional`](https://github.com/purescript-contrib/purescript-argonaut-codecs/blob/master/src/Data/Argonaut/Decode/Combinators.purs#L20) was exported from `Data.Argonaut`.

This issue depends on https://github.com/purescript-contrib/purescript-argonaut-codecs/issues/33 being merged and released.

**Comment by thomashoneyman** [comment]
Closed in #42!
