### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by joneshf** [purescript-contrib/purescript-argonaut#9]
Too many people lately have been asking questions about it. It's way out of date, so it should be updated.

**Comment by davidchambers** [comment]
I'd love to see an example of a function which takes a record containing maybes and returns a JavaScript object with nullable fields.

```purescript
-- input
{ foo: Just 42, bar: Nothing }
```

```javascript
// output
{ foo: 42, bar: null }
```

**Comment by jdegoes** [comment]
Agreed.

As for nullable, if you use `Maybe` and just call `encodeJson` on your `Maybe`, then `Nothing` will automatically be encoded as `null`.

**Comment by davidchambers** [comment]
> As for nullable, if you use `Maybe` and just call `encodeJson` on your `Maybe`, then `Nothing` will automatically be encoded as `null`.

Is it possible to encode a whole record, or must one apply `encodeJson` to each value?

**Comment by jdegoes** [comment]
You must encode each field separately because there is no way to abstract over records at present.
